version: '3'
services:
  CytoPy:
    image: burtonrj/cytopy:latest
    ports:
      - "8888:8888"
    volumes:
    - /DockerData/notebooks:/home/notebooks
    - /DockerData/hdf:/home/hdf
    working_dir: "/home"
    links:
      - mongodb
  mongodb:
    image: mongo:4.4-bionic
