[build-system]
requires = [
    # The minimum setuptools version is specific to the PEP 517 backend,
    # and may be stricter than the version required in `setup.py`
    "setuptools>=40.8.0",
    "wheel",
    # Minimum requirement for HDBSCAN 
    "cython"
]
