from ..data.experiment import Experiment, FileGroup
from ..feedback import progress_bar, vprint
from .dim_reduction import dimensionality_reduction
from .sampling import density_dependent_downsampling, faithful_downsampling, uniform_downsampling
from .transforms import scaler
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KernelDensity
from scipy.spatial.distance import jensenshannon as jsd
from scipy.stats import entropy as kl
from scipy.cluster import hierarchy
from scipy.spatial import distance
from multiprocessing import Pool, cpu_count
from collections import defaultdict, OrderedDict
from KDEpy import FFTKDE
from typing import Dict
from warnings import warn
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import math


def bw_optimisation(data: pd.DataFrame,
                    features: list,
                    kernel: str = "gaussian",
                    bandwidth: tuple = (0.01, 0.1, 10),
                    cv: int = 10,
                    verbose: int = 1):
    """
    Using GridSearchCV and the Scikit-Learn implementation of KDE, find the optimal
    bandwidth for the given data using grid search cross-validation

    Parameters
    ----------
    data: pd.DataFrame
    features: features
    kernel: str (default="gaussian")
    bandwidth: tuple (default=(0.01, 0.1, 20))
    cv: int (default=10)
    verbose: int (default=1)

    Returns
    -------
    float
    """
    bandwidth = np.linspace(*bandwidth)
    kde = KernelDensity(kernel=kernel)
    grid = GridSearchCV(estimator=kde,
                        param_grid={"bandwidth": bandwidth},
                        cv=cv,
                        n_jobs=-1,
                        verbose=verbose)
    grid.fit(data[features])
    return grid.best_params_.get("bandwidth")


def _common_features(data: Dict[str, pd.DataFrame]):
    features = [df.columns.tolist() for df in data.values()]
    return list(set(features[0]).intersection(*features))


def covar_euclidean_norm(data: Dict[str, pd.DataFrame],
                         verbose: bool = True):
    """

    This is performed as described in Li et al paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5860171/) on
    DeepCyTOF: for every 2 samples i, j compute the euclidean norm of the difference between their covariance matrics
    and then select the sample with the smallest average distance to all other samples.

    This is an optimised version of supervised.ref.calculate_red_sample that leverages the multi-processing library
    to speed up operations

    Parameters
    ----------
    data: dict
    verbose: bool, (default=True)
        Feedback
    Returns
    -------
    str
        Sample ID of reference sample
    """
    feedback = vprint(verbose)
    feedback('Calculate covariance matrix for each sample...')
    # Calculate covar for each
    features = _common_features(data=data)
    covar = {k: np.cov(v[features], rowvar=False) for k, v in data.items()}
    feedback('Search for sample with smallest average euclidean distance to all other samples...')
    # Make comparisons
    sample_ids = list(data.keys())
    n = len(sample_ids)
    norms = np.zeros(shape=[n, n])
    ref_ind = None
    for i, sample_i in enumerate(sample_ids):
        for j, sample_j in enumerate(sample_ids):
            cov_diff = covar.get(sample_i) - covar.get(sample_j)
            norms[i, j] = np.linalg.norm(cov_diff, ord='fro')
            norms[j, i] = norms[i, j]
            avg = np.mean(norms, axis=1)
            ref_ind = np.argmin(avg)
    return sample_ids[int(ref_ind)]


def scale_data(data: OrderedDict,
               method: str or None = "standard",
               **kwargs):
    """
    Given a dictionary of events data as generated by `load_and_sample`, scale the data using
    a valid scale method (see CytoPy.flow.transforms.scaler)

    Parameters
    ----------
    data: dict
    method: str (default="standard")
    kwargs: dict
        Keywords passed to scaler

    Returns
    -------
    dict
    """
    scaled = OrderedDict()
    for k, df in data.items():
        scaled[k] = pd.DataFrame(scaler(data=df.values,
                                        scale_method=method,
                                        return_scaler=False,
                                        **kwargs),
                                 columns=df.columns)
    return scaled


def load_and_sample(experiment: Experiment,
                    sample_ids: list,
                    population: str,
                    sample_size: int or float,
                    sampling_method: str or None = "uniform",
                    transform: str = "logicle",
                    **kwargs):
    """
    Load sample data from experiment and return as a dictionary of Pandas DataFrames.

    Parameters
    ----------
    experiment: Experiment
    sample_ids: list
    sample_size: int or float (optional)
        Total number of events to sample from each file
    sampling_method: str
    transform: str
    population: str
    kwargs
        Additional keyword arguments for sampling method

    Returns
    -------
    OrderedDict
    """
    files = [experiment.get_sample(s) for s in sample_ids]
    data = OrderedDict()
    for f in progress_bar(files, verbose=True):
        data[f.primary_id] = _sample_filegroup(filegroup=f,
                                               sample_size=sample_size,
                                               sampling_method=sampling_method,
                                               transform=transform,
                                               population=population,
                                               **kwargs)
    return data


def kde_wrapper(data: pd.DataFrame,
                kernel: str,
                bw: float or str):
    return FFTKDE(kernel=kernel, bw=bw).fit(data.values)()[1]


def _sample_filegroup(filegroup: FileGroup,
                      population: str,
                      transform: str or None,
                      sample_size: int or float = 5000,
                      sampling_method: str or None = None,
                      **kwargs) -> pd.DataFrame:
    """
    Given a FileGroup and the name of the desired population, load the
    population with transformations applied and downsample if necessary.

    Parameters
    ----------
    filegroup: FileGroup
    population: str
    transform: str (optional)
    sample_size: int or float (optional)
    sampling_method: str (optional)

    Returns
    -------
    Pandas.DataFrame
    """
    data = filegroup.load_population_df(population=population,
                                        transform=transform)
    if sampling_method == "uniform":
        return uniform_downsampling(data=data, sample_size=sample_size)
    if sampling_method == "density":
        return density_dependent_downsampling(data=data, sample_size=sample_size, **kwargs)
    if sampling_method == "faithful":
        return faithful_downsampling(data=data, **kwargs)
    return data


def marker_variance(data: OrderedDict,
                    reference: str,
                    comparison_samples: list or None = None,
                    markers: list or None = None,
                    figsize: tuple = (10, 10),
                    xlim: tuple or None = None,
                    verbose: bool = True,
                    kernel: str = "gaussian",
                    kde_bw: str or float = "silverman",
                    **kwargs):
    """
    Compare the kernel density estimates for each marker in the associated experiment for the given
    comparison samples. The estimated distributions of the comparison samples will be plotted against
    the reference sample.

    Parameters
    ----------
    data: dict
    reference: str
    comparison_samples: list
        List of valid sample IDs for the associated experiment
    markers: list (optional)
        List of markers to include (defaults to all available markers)
    figsize: figsize (default=(10,10))
    xlim: tuple (optional)
        x-axis limits
    verbose: bool (default=True)
    kernel: str (default="gaussian")
    kde_bw: str or float (default="silverman")
    kwargs: dict
        Additional kwargs passed to Matplotlib.Axes.plot call

    Returns
    -------
    matplotlib.Figure
    """
    assert reference in data.keys(), "Reference absent from given data"
    comparison_samples = comparison_samples or [x for x in data.keys() if x != reference]
    fig = plt.figure(figsize=figsize)
    markers = markers or data.get(reference).columns.tolist()
    i = 0
    nrows = math.ceil(len(markers) / 3)
    fig.suptitle(f'Per-channel KDE, Reference: {reference}', y=1.05)
    for marker in progress_bar(markers, verbose=verbose):
        i += 1
        ax = fig.add_subplot(nrows, 3, i)
        x, y = (FFTKDE(kernel=kernel,
                       bw=kde_bw)
                .fit(data.get(reference)[marker].values)
                .evaluate())
        ax.plot(x, y, color="b", **kwargs)
        ax.fill_between(x, 0, y, facecolor="b", alpha=0.2)
        ax.set_title(f'Total variance in {marker}')
        if xlim:
            ax.set_xlim(xlim)
        for comparison_sample_id in comparison_samples:
            if comparison_sample_id not in data.keys():
                warn(f"{comparison_sample_id} is not a valid ID")
                continue
            if marker not in data.get(comparison_sample_id).columns:
                warn(f"{marker} missing from {comparison_sample_id}, this marker will be ignored")
            else:
                x, y = (FFTKDE(kernel=kernel,
                               bw=kde_bw)
                        .fit(data.get(comparison_sample_id)[marker].values)
                        .evaluate())
                ax.plot(x, y, color="r", **kwargs)
                if ax.get_legend() is not None:
                    ax.get_legend().remove()
        ax.set(aspect="auto")
    fig.tight_layout()
    return fig


def dim_reduction_grid(data: OrderedDict,
                       reference: str,
                       features: list,
                       comparison_samples: list or None = None,
                       figsize: tuple = (10, 10),
                       method: str = 'PCA',
                       kde: bool = False,
                       verbose: bool = True,
                       dim_reduction_kwargs: dict or None = None):
    """
    Generate a grid of embeddings using a valid dimensionality reduction technique, in each plot a reference sample
    is shown in blue and a comparison sample in red. The reference sample is conserved across all plots.

    Parameters
    ------------
    data: dict
    reference: str
        This sample will appear in red as a comparison
    comparison_samples: list
        List of samples to compare to reference (blue)
    features: list
        List of features to use for dimensionality reduction
    figsize: tuple, (default=(10,10))
        Size of figure
    method: str, (default='PCA')
        Method to use for dimensionality reduction (see flow.dim_reduction)
    dim_reduction_kwargs: dict
    kde: bool, (default=False)
        If True, overlay with two-dimensional PDF estimated by KDE
    verbose: bool (default=True)

    Returns
    -------
    None
        Plot printed to stdout
    """
    assert reference in data.keys(), "Reference absent from given data"
    comparison_samples = comparison_samples or [x for x in data.keys() if x != reference]
    dim_reduction_kwargs = dim_reduction_kwargs or {}
    fig = plt.figure(figsize=figsize)
    nrows = math.ceil(len(comparison_samples) / 3)
    reference = data.get(reference).copy()
    reference['label'] = 'Target'
    assert all([f in reference.columns for f in features]), \
        f'Invalid features; valid are: {reference.columns}'
    reference, reducer = dimensionality_reduction(reference,
                                                  features=features,
                                                  method=method,
                                                  n_components=2,
                                                  return_reducer=True,
                                                  **dim_reduction_kwargs)
    i = 0
    fig.suptitle(f'{method}, Reference: {reference}', y=1.05)
    for sample_id, df in progress_bar(data.items(), verbose=verbose):
        if sample_id == reference:
            continue
        if not all([f in df.columns for f in features]):
            warn(f'Features missing from {sample_id}, skipping')
            continue
        i += 1
        df['label'] = 'Comparison'
        ax = fig.add_subplot(nrows, 3, i)
        embeddings = reducer.transform(df[features])
        x = f'{method}1'
        y = f'{method}2'
        ax.scatter(reference[x], reference[y], c='blue', s=4, alpha=0.2)
        if kde:
            sns.kdeplot(reference[x], reference[y], c='blue', n_levels=100, ax=ax, shade=False)
        ax.scatter(embeddings[:, 0], embeddings[:, 1], c='red', s=4, alpha=0.1)
        if kde:
            sns.kdeplot(embeddings[:, 0], embeddings[:, 1], c='red',
                        n_levels=100, ax=ax, shade=False)
        ax.set_title(sample_id)
        ax.set_yticklabels([])
        ax.set_xticklabels([])
        ax.set(aspect='auto')
    fig.tight_layout()
    return fig


class SimilarityMatrix:
    """
    Class for assessing the degree of variation observed in a single experiment. This can be
    useful for determining the influence of batch effects in your cytometry experiment.

    Attributes
    -----------
    experiment: Experiment
        Experiment to investigate
    root_population: str
        Population to sample from e.g. T cells or Monocytes
    samples: list (optional)
        Samples to include in investigation (if None, uses all samples)
    sample_size: int (default=5000)
        Default sample size when taking uniform samples of biological data
    transform: str (default="logicle")
        How to transform the data prior to processing
    verbose: bool (default=True)
        Whether to provide feedback
    njobs: int (default=-1)
        Number of parallel jobs to run
    kde_kernel: str (default="gaussian")
        Kernel to use for KDE, for options see KDEpy.FFTKDE
    kde_bw: str or float (default="ISJ"
        Bandwidth/bandwidth estimation method to use for KDE. See KDEpy for options.
        Defaults too improved Sheather Jones (ISJ) algorithm, which does not assume normality
        and is robust to multimodal distributions. If you need to speed up results, change this to
        'silvermans' which is less accurate but less computationally intensive.
    """

    def __init__(self,
                 data: OrderedDict,
                 reference: str or None = None,
                 verbose: bool = True,
                 njobs: int = -1,
                 scale: str or None = None,
                 kde_kernel: str = "gaussian",
                 kde_bw: str or float = "silverman",
                 scale_kwargs: dict or None = None):
        assert reference in data.keys(), "Invalid reference, not present in given data"
        scale_kwargs = scale_kwargs or {}
        self.verbose = verbose
        self.print = vprint(verbose)
        self.kde_cache = dict()
        self.njobs = njobs
        self.kde_kernel = kde_kernel
        self._kde_bw = kde_bw
        self.reference = reference
        if self.njobs < 0:
            self.njobs = cpu_count()
        if scale is not None:
            self.data = scale_data(data=data, method=scale, **scale_kwargs)

    @property
    def kde_bw(self):
        return self._kde_bw

    @kde_bw.setter
    def kde_bw(self, x: str or float):
        if isinstance(x, str):
            valid = list(FFTKDE._bw_methods.keys()) + ["cv"]
            assert x in valid, \
                f"If kde_bw is a string value, should either be one of: {valid}"
        else:
            assert isinstance(x, float), "kde_bw should be a float or 'silverman' or 'ISJ'"
        self._kde_bw = x

    def clean_cache(self):
        """
        Clears the KDE cached results

        Returns
        -------
        None
        """
        self.kde_cache = {}

    def _estimate_pdf(self,
                      sample_id: str,
                      features: list,
                      df: pd.DataFrame,
                      **kwargs):
        """
        Given a sample ID and its events dataframe, estimate the PDF by KDE with the option
        to perform dimensionality reduction first. Resulting PDF is saved to kde_cache.

        Parameters
        ----------
        sample_id: str
        df: Pandas.DataFrame
        features: list

        Returns
        -------
        None
        """
        bw = self.kde_bw
        if bw == "cv":
            bw = bw_optimisation(data=df, features=features, **kwargs)
        df = df[features].copy().select_dtypes(include=['number'])
        kde = FFTKDE(kernel=self.kde_kernel, bw=bw)
        self.kde_cache[sample_id] = kde.fit(df.values).evaluate()[1]

    def calc_divergence(self,
                        target_id: str,
                        features: list,
                        data: dict or None = None,
                        distance_metric: str or callable = 'jsd') -> np.array:
        """
        Given some target sample ID, estimate the PDF (with the option to perform dimensionality reduction first) and
        calculate the statistical distance between the target and the PDF of all other samples in the associated
        experiment.

        Parameters
        ----------
        target_id: str
            Should be a valid sample ID for the associated experiment
        features: list
            Markers to be included in multidimensional KDE
        data: dict (optional)
            If provided, data will be sourced from this dictionary rather than making a call to `load_and_sample`. If given
            then value given for sample is ignored.
        distance_metric: callable or str (default='jsd')
            Either a callable function to calculate the statistical distance or a string value; options are:
                * jsd: Jensson-shannon distance
                * kl:Kullback-Leibler divergence (entropy)

        Returns
        -------
        list
            List of statistical distances, with results given as a list of nested tuples of type: (sample ID, distance).
        """
        # Assign distance metric func
        metrics = {"kl": kl,
                   "jsd": jsd}
        if isinstance(distance_metric, str):
            assert distance_metric in ['jsd', 'kl'], \
                'Invalid divergence metric must be one of either jsd, kl, or a callable function]'
            distance_metric = metrics.get(distance_metric)
        for i, (sample_id, df) in enumerate(data.items()):
            if sample_id not in self.kde_cache.keys():
                self.print(f"({i}) Estimating pdf for {sample_id}")
                self._estimate_pdf(sample_id=sample_id,
                                   df=df,
                                   features=features)
        return [(name, distance_metric(self.kde_cache.get(target_id), q))
                for name, q in self.kde_cache.items()]

    def _generate_reducer(self,
                          features: list,
                          n_components: int,
                          dim_reduction_method: str,
                          **kwargs):
        reference = self.data.get(self.reference)
        ref_embeddings, reducer = dimensionality_reduction(data=reference,
                                                           method=dim_reduction_method,
                                                           features=features,
                                                           return_reducer=True,
                                                           return_embeddings_only=True,
                                                           n_components=n_components,
                                                           **kwargs)
        return reducer

    def _dim_reduction(self,
                       reducer: object,
                       col_names: list):
        with Pool(self.njobs) as pool:
            self.print("...performing dimensionality reduction")
            embeddings = list(progress_bar(pool.imap(reducer.transform, self.data.values()),
                                           verbose=self.verbose,
                                           total=len(self.data.values())))
        embeddings = {k: em for k, em in zip(self.data.keys(),
                                             pd.DataFrame(embeddings, columns=col_names))}
        return embeddings

    def _pairwise_stat_dist(self,
                            embeddings: dict,
                            features: list,
                            distance_metric: str):
        self.print("Calculating pairwise statistical distances...")
        distance_df = pd.DataFrame()
        for s in progress_bar(embeddings.keys(), verbose=self.verbose):
            distances = self.calc_divergence(target_id=s,
                                             features=features,
                                             data=embeddings.get(s),
                                             distance_metric=distance_metric)
            name_distances = defaultdict(list)
            for n, d in distances:
                name_distances[n].append(d)
            name_distances = pd.DataFrame(name_distances)
            name_distances["sample_id"] = s
            distance_df = pd.concat([distance_df, name_distances])
        return distance_df

    def similarity_matrix(self,
                          figsize: tuple = (12, 12),
                          distance_metric: str or callable = 'jsd',
                          clustering_method: str = 'average',
                          features: None or list = None,
                          dim_reduction_method: str = "PCA",
                          dim_reduction_kwargs: dict or None = None,
                          cluster_plot_kwargs: dict or None = None):
        """
        Generate a heatmap of pairwise statistical distances with the axis clustered using agglomerative clustering.

        Parameters
        ----------
        figsize: tuple (default=(12,12))
            Figure size
        distance_metric: callable or str (default='jsd')
            Either a callable function to calculate the statistical distance or a string value; options are:
                * jsd: Jensson-shannon distance
                * kl:Kullback-Leibler divergence (entropy)
        clustering_method: str
            Method passed to call to scipy.cluster.heirachy
        features: list (optional)
            List of markers to use in analysis. If not given, will use all available markers.
        dim_reduction_method: str (default="PCA")
            Dimension reduction method, see CytoPy.flow.dim_reduction. Set to None to not reduce first
        dim_reduction_kwargs: dict
            Keyword arguments for dimension reduction method, see CytoPy.flow.dim_reduction
        cluster_plot_kwargs: dict
            Additional keyword arguments passed to Seaborn.clustermap call

        Returns
        -------
        Array, Array, ClusterGrid
            Linkage array, ordered array of sample IDs and seaborn ClusterGrid object
        """
        # Set defaults
        dim_reduction_kwargs = dim_reduction_kwargs or {}
        cluster_plot_kwargs = cluster_plot_kwargs or {}
        if distance_metric == "kl":
            warn("Kullback-Leiber Divergence chosen as statistical distance metric, KL divergence "
                 "is an asymmetrical function and as such it is not advised to use this metric for the "
                 "similarity matrix'")

        features = features or self.data.get(self.reference).columns.tolist()
        # Create the reducer
        n_components = dim_reduction_kwargs.get("n_components", 2)
        reducer = self._generate_reducer(features=features,
                                         n_components=n_components,
                                         dim_reduction_method=dim_reduction_method,
                                         **dim_reduction_kwargs)
        features = [f"embedding{i + 1}" for i in range(n_components)]
        embeddings = self._dim_reduction(reducer=reducer, col_names=features)
        # Generate distance matrix
        distance_df = self._pairwise_stat_dist(embeddings=embeddings,
                                               distance_metric=distance_metric,
                                               features=features)
        # Perform hierarchical clustering
        r = distance_df.drop('sample_id', axis=1).values
        c = distance_df.drop('sample_id', axis=1).T.values
        row_linkage = hierarchy.linkage(distance.pdist(r), method=clustering_method)
        col_linkage = hierarchy.linkage(distance.pdist(c), method=clustering_method)

        if distance_metric == 'jsd':
            center = 0.5
        else:
            center = 0
        g = sns.clustermap(distance_df.set_index('sample_id'),
                           row_linkage=row_linkage,
                           col_linkage=col_linkage,
                           method=clustering_method,
                           center=center,
                           cmap="vlag",
                           figsize=figsize,
                           **cluster_plot_kwargs)
        ax = g.ax_heatmap
        ax.set_xlabel('')
        ax.set_ylabel('')
        return row_linkage, distance_df.sample_id.values, g
